credentials:
  accessKey: "minio-admin"
  secretKey: "minio-admin"

ingress:
  type: "nginx" # options: "istio", "openshift"
  subPath:
    enabled: false
    baseDomain: "hello.webapp.me"
    api: /minio/api
    ui: /minio/ui
  rootDomain:
    enabled: true
    api: "minio-api.hello.webapp.me"
    ui: "minio-ui.hello.webapp.me"

persistentVolume:
  storageClass: "standard"
  size: "10Gi"
