{{- if .Values.wow.enabled }}
{{- if eq .Values.ingress.type "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: {{ .Values.namespace }}
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.rootDomain.api }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-api
            port:
              number: 80
  - host: {{ .Values.ingress.rootDomain.ui }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-ui
            port:
              number: 80
{{- else }}
{{- printf "Skipping nginx ingress creation" | indent 2 }}
{{- end }}
