apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-creds
  namespace: {{ .Values.namespace }}
stringData:
  MINIO_ROOT_USER: {{ .Values.credentials.accessKey }}
  MINIO_ROOT_PASSWORD: {{ .Values.credentials.secretKey }}
